# podman compose --file podman-compose.yml up --detach
version: '3.8'
services:
  mysql:
    image: docker.io/library/mysql:8.4.2
    container_name: backend-mysql
    restart: 'unless-stopped'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 33006:3306
    expose:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root_password

  phpmyadmin:
    image: docker.io/library/phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_PASSWORD: root_password
        PMA_USER: root
    ports:
        - 8080:80
volumes:
  mysql:
