# podman compose --file podman-compose.yml up --detach
version: '3.8'
services:
  mysql:
    image: docker.io/library/mysql:8.4.2
    container_name: backend-mysql
    restart: 'unless-stopped'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 33006:3306
    environment:
        MYSQL_ROOT_PASSWORD: root_password

volumes:
  mysql:
