// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type RedditCloneComment struct {
	IDComment   int32
	CreatedDate time.Time
	EditedDate  sql.NullTime
	IDPost      int32
	ParentID    int32
	IDUser      int32
}

type RedditClonePost struct {
	IDPost      int32
	Title       string
	Link        sql.NullString
	Text        sql.NullString
	CreatedDate time.Time
	EditedDate  sql.NullTime
	IDSubreddit int32
	IDUser      int32
}

type RedditCloneSubreddit struct {
	IDSubreddit int32
	Url         string
	Name        string
	Description sql.NullString
	IDUser      sql.NullInt32
}

type RedditCloneUser struct {
	IDUser         int32
	UserName       string
	DisplayName    sql.NullString
	Email          string
	HashedPassword string
}
